### ISSUE TITLE
Random announcements "Grinder" still !

### ISSUE THREAD

**Issue by GreatTeacherOni** [NekoNova/RareTracker#7]
Hey i'm getting rare tracker announcement in the captial (Thayd) whenever someone is riding on his "Grinder" Mount. There seems to be a monster called grinder aswell i guess, but this is annoying :P

**Comment by coding-red-panda** [comment]
I will see if I can add something to rule out mounts.

**Comment by coding-red-panda** [comment]
should be fixed in v2.0.3
If not, reopen the issue please.

**Comment by GreatTeacherOni** [comment]
Issue still persists! It is finding the Grinder Mount that is standing as a display behind the Hoverboard Flair Imports Vendor. In south of Thayd.

**Comment by AMGarkin** [comment]
FYI: For Grinder in Thyad unitCreated:GetType() returns "Simple" and unitCreated:GetLevel() returns nil. Maybe filter out all units which doesn't have level?

**EDIT:**
I have changed

``` Lua
  if unitCreated:GetType() == "Mount" then return end
```

to:

``` Lua
  if unitType ~= "NonPlayer" then return end
```

and it seems to be working.

**Comment by coding-red-panda** [comment]
will implement that this evening and see what it says. Need to check if Discoveries still work as well then.
Because if they are flagged as "Simple" as well, then I need to change the tracking logic.
